### ISSUE TITLE
空氣品質資訊系統

### ISSUE THREAD

**Issue by e22346845** [karateboy/SIP#1]
空氣品質資訊系統--前3點請於3月3日完成
(1)	斷線問題，驗收前(3月初)通知Aragorn再次確認
(2)	數據更新不一致之問題，須將數據傳給Aragorn，確認能否訂閱月報、年報數據，以更新過去數據
(3)	依訂閱之月報時間，會將之前的空品數據上傳給Aragorn，再麻煩煩更新PSI排名
(4)    建議後續須設定AQI功能、計算各污染物之最大小時第八大值

**Comment by karateboy** [comment]
Issue的用法是, 一個問題/功能需求列一個issue.
這樣才比較容易管理. 
另外空氣品質資訊系統, 我是放在另一個repository, 所以我把以上的問題改列到
[https://github.com/karateboy/YL/issues](url)

這個issue就此關閉

**Comment by e22346845** [comment]
了解~感謝^^
