### ISSUE TITLE
新增警報內容

### ISSUE THREAD

**Issue by e22346845** [karateboy/SIP#10]
Alan表示需要 警報簡訊的部分，只有說明該污染物超標，有點空虛的感覺，
## 希望能呈現該污染物之濃度以及該污染物法規濃度(警報值濃度)，
以方便接收簡訊者讀取內容，感謝您！

**Comment by karateboy** [comment]
已修改

**Comment by e22346845** [comment]
OK~已驗證，辛苦嚕，感謝！
