### ISSUE TITLE
特殊性工業區監測系統

### ISSUE THREAD

**Issue by e22346845** [karateboy/SIP#2]
特殊性工業區監測系統--這3點請於3月3日前完成
1.	報表下載功能異常(pdf及Excel均無法)
2.	有效率筆數計算有誤，要增加應測筆數及有效率
3.	數據稽核功能之設定：
(1)	各項請Aragorn開啟設定啟用
(2)	有歷史數據檢核功能，可設定稽核標準後重新檢核，確認所設值是否洽當
(3)	除了簡訊發送功能外，須另設有mail發送功能，夥伴們提供發送mail之信箱相關設定資料給Aragorn

**Comment by e22346845** [comment]
特殊性工業區監測系統--這4點請於3月10日前完成
1.	即時數據的取得來源與時間：數據取得為局內伺服器，夥伴們取得伺服器存取權限後，提供Aragron確認數據延遲原因及協助改善。
2.	警報重複問題：當超過多項警報時，可合併通報(mail及簡訊)
3.	報表輸出時，測站測項希望設定多個選項功能，打包為ZIP檔案下載
4.	查詢數據時，希望能設定複選之功能

**Comment by karateboy** [comment]
將Issues 拆開列...將原本的關閉
