### ISSUE TITLE
有效率筆數計算有誤

### ISSUE THREAD

**Issue by karateboy** [karateboy/SIP#6]
有效率筆數計算有誤，要增加應測筆數及有效率

**Comment by karateboy** [comment]
fixed

**Comment by karateboy** [comment]
已修正, 請驗證後關閉

**Comment by e22346845** [comment]
報表查詢-->監測報表-->月報-->發現一月以前的數據 有效率未修正

**Comment by e22346845** [comment]
且 希望在月報那邊 可以新增 有效筆數(小時) 及 應測筆數 ,謝謝！

**Comment by karateboy** [comment]
一月的月報沒問題呀?
![image](https://cloud.githubusercontent.com/assets/1067042/23260652/ce8c63ba-fa0d-11e6-87c8-562c992a849a.png)

**Comment by e22346845** [comment]
是報表查詢-->監測報表-->月報
不是月份時報表，且希望月份時報表也開放下載功能，麻煩了，感謝！
![default](https://cloud.githubusercontent.com/assets/25893727/23284890/d6a449fe-fa68-11e6-953d-5d1cc930103d.JPG)

**Comment by karateboy** [comment]
已修正

**Comment by e22346845** [comment]
報表查詢-->監測報表-->月報 
有無效數據，為何有效率是100%?
月報有效率的部分，**## 麻煩也呈現"有效筆數"及"應測筆數"(單位以小時來算，如720小時或744小時)，謝謝！**
這個比較急，105SIP期中報告需要用到，這兩天要交，再麻煩你了，感謝！

![1](https://cloud.githubusercontent.com/assets/25893727/23441408/12b21f32-fe5d-11e6-9851-f980820bc89d.JPG)
![2](https://cloud.githubusercontent.com/assets/25893727/23441409/12b4edac-fe5d-11e6-8bf5-31e24fe38e9f.JPG)

**Comment by karateboy** [comment]
Sorry 已經上傳了
先前弄好只放在我的電腦, 還沒上傳更新網站

**Comment by e22346845** [comment]
不好意思,有效筆數要從每天有多少有效筆數，累積到整月，如下圖所示，是要呈現# 整個月有多少筆有效時數，並不是有效日數，再麻煩一下了，謝謝！

![default](https://cloud.githubusercontent.com/assets/25893727/23447341/332bae90-fe85-11e6-9c91-f1b7a06bbf4c.JPG)

**Comment by karateboy** [comment]
已經修正上傳...

**Comment by e22346845** [comment]
可以了，太感謝了！辛苦了XD！
