### ISSUE TITLE
數據稽核功能之設定

### ISSUE THREAD

**Issue by karateboy** [karateboy/SIP#8]
(1)	各項請Aragorn開啟設定啟用
(2)	有歷史數據檢核功能，可設定稽核標準後重新檢核，確認所設值是否洽當
(3)	除了簡訊發送功能外，須另設有mail發送功能，夥伴們提供發送mail之信箱相關設定資料給Aragorn

**Comment by karateboy** [comment]
已經修改...
歷史數據檢核明天給你...其他已經完成

**Comment by karateboy** [comment]
已經完成

**Comment by e22346845** [comment]
請問怎麼查閱 "設定稽核標準後重新檢核，確認所設值是否洽當"，
主要需要的功能為，修改設定的標準後，可以選擇時間範圍內，超標之污染物、濃度、日數、時數、日期，謝謝！

**Comment by karateboy** [comment]
我建議一個瀏覽器開兩個視窗:
1. 系統管理>資料檢核設定
2. 報表查詢>數據檢核報表
在視窗1修改"資料檢核設定", 到視窗2"重新檢核"就可以看到在區段時間內, 有多少資料被註記.
"重新檢核"不會發警報, 所以不用擔心.

至於報表查詢>數據檢核報表的"查詢", 是查詢目前有哪些資料被註記

**Comment by karateboy** [comment]
類似這樣 (我設定土庫相對濕度最大50%)
![image](https://cloud.githubusercontent.com/assets/1067042/23512266/010a5cc4-ff9b-11e6-98a9-f8478c171016.png)

**Comment by e22346845** [comment]
OK  看得懂了  我們研究一下看看  感謝!!!

**Comment by e22346845** [comment]
Aragorn,有些檢核的設定我們看不太懂，想向你詢問一下你在以下的設定值，是如何計算的，可否列公式讓我們參考一下，謝謝！
1.三小時變化驗證值  
2.四小時變化驗證值 
3.分鐘值超過內控 - 內容說明 "分數"值在一小時內超過內控值筆數 ，是不是打錯了!?
4.分鐘值回傳超時 - 內容說明 "分數"值資料回傳檢查，是否也打錯了!?

以上4點，希望可以知道其計算公式，再麻煩了，謝謝！

**Comment by karateboy** [comment]
小時變化驗證是工業局訂的標準, 計算方式在網頁上有寫.
如: 連續三小時測值差距如超過系統設定之絕對值及比例, 該測項小時值註記為異常值
那可以設定絕對值和比例...

3. 是"分鐘值" 鍵盤誤

**Comment by e22346845** [comment]
Aragorn您好,檢核設定的部分，希望再做些新增功能
1.報表查詢>資料檢核報表>在這邊複選物種時，會出現"沒有匹配結果"，希望這邊可以複選，謝謝！
2.報表查詢>資料檢核報表>在這邊選擇物種後，希望這邊指定要幾筆數據，來得到要設定多高的污染濃度，謝謝！
不好意思又麻煩您了，謝謝！

**Comment by karateboy** [comment]
1. 測項可以複選, 沒有匹配結果, 表示你設定的"資料檢核"規則都沒有觸發. 這其實還蠻正常的吧. 
2. 這功能目前沒打算做. 這比較是資料統計分析...

**Comment by e22346845** [comment]
第一張圖 選擇CO 有出現超標之時間、濃度
![1](https://cloud.githubusercontent.com/assets/25893727/23753103/228bf2c2-0513-11e7-94ce-c37508cb05f5.PNG)

第二張圖 複選CO及NO 則出現 沒有匹配結果
![2](https://cloud.githubusercontent.com/assets/25893727/23753177/656ae1c0-0513-11e7-9a59-7352972dfb8e.PNG)

請問這應該是有誤吧@@?

**Comment by karateboy** [comment]
哈...看來是有bug...應該是任一測項有註記...不是所有測項都有註記

**Comment by e22346845** [comment]
嗯@@再麻煩修正一下了,感謝!!

**Comment by karateboy** [comment]
1.0.8 已修正
